In [ ]:
import numpy as np
import h5py

arr = np.random.randn(1000)

with h5py.File('groups.hdf5', 'w') as f:
    g = f.create_group('Base_Group')
    gg = g.create_group('Sub_Group')

    d = g.create_dataset('default', data=arr)
    dd = gg.create_dataset('default', data=arr)



In [ ]:
import numpy as np

data = np.array([[1, 1, 1], [1, 1, 1], [1, 2, 2]])
# to_columns = np.zeros((data.shape[1], 2)) 
# data = np.append(data, to_columns, axis=1)

print(data)
print(data[1:, -2])

In [ ]:

with h5py.File('groups.hdf5', 'r') as f:
   d = f['Base_Group/default']
   dd = f['Base_Group/Sub_Group/default']
   print(d[:4])
   print(dd[4:4])

In [10]:
import work_with_file as wwf
import numpy as np 
values = wwf.values_from_file('array.txt')

print(np.c_[values, np.zeros(values.shape[0])])

['3 -5 6 1\n', '2 4 -5 10\n', '1 -3 6 -15']
[[  3.  -5.   6.   1.   0.]
 [  2.   4.  -5.  10.   0.]
 [  1.  -3.   6. -15.   0.]]
